export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST";
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS";
export const ORDER_CREATE_FAILED = "ORDER_CREATE_FAILED";

export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_FAILED = "ORDER_DETAILS_FAILED";

export const ORDER_PAY_REQUEST = "ORDER_PAY_REQUEST";
export const ORDER_PAY_SUCCESS = "ORDER_PAY_SUCCESS";
export const ORDER_PAY_FAILED = "ORDER_PAY_FAILED";
export const ORDER_PAY_RESET = "ORDER_PAY_RESET";

export const MY_ORDERS_LIST_REQUEST = "MY_ORDERS_LIST_REQUEST";
export const MY_ORDERS_LIST_SUCCESS = "MY_ORDERS_LIST_SUCCESS";
export const MY_ORDERS_LIST_FAILED = "MY_ORDERS_LIST_FAILED";
export const MY_ORDERS_LIST_RESET = "MY_ORDERS_LIST_RESET";

export const ORDERS_LIST_REQUEST = "ORDERS_LIST_REQUEST";
export const ORDERS_LIST_SUCCESS = "ORDERS_LIST_SUCCESS";
export const ORDERS_LIST_FAILED = "ORDERS_LIST_FAILED";
// export const ORDERS_LIST_RESET = "ORDERS_LIST_RESET";
